# Generated by Django 4.2.6 on 2023-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drink", "0006_alter_notebook_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_trashed",
            field=models.BooleanField(default=False),
        ),
    ]
